name: Build

on:
  push:
    branches: [ "CI" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt install -y clang libboost-all-dev qtbase5-dev ninja-build libqt5svg5-dev python3-pip

    - name: Install conan
      run: sudo pip install conan

    - name: Configure CMake
      run: cmake -G Ninja -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build
