name: Build

on:
  push:
    branches: [ "CI" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get tags
      run: git fetch --tags origin

    - name: Test version
      run: git describe --long --match "[0-9]*" HEAD
    
    - name: Install dependencies
      run: sudo apt install -y clang libboost-all-dev ninja-build qtbase5-dev libqt5svg5-dev python3-pip

    - name: Install conan
      run: sudo pip install conan==1.59.0

    - name: Configure CMake
      run: cmake -G Ninja -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build
