name: clang-tidy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  clang_tidy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Get tags
        run: git fetch --tags origin

      - name: Install dependencies
        run: sudo apt install -y gcc-12 g++-12 ninja-build qtbase5-dev libqt5svg5-dev python3-pip grep

      - name: Install conan
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install conan

      - name: Cache Conan packages

        uses: actions/cache@v2
        with:
          path: ~/.conan2
          key: conan-ubuntu-24.04-gnu-${{ hashFiles('**/conanfile.txt') }}

      - name: Install conan dependencies
        run: |
          source venv/bin/activate
          conan install . -s build_type=Release -of .conan/gcc --build=missing -pr:a .conan/gcc/profile

      - name: Configure CMake
        run: cmake --preset="ci_gnu_release"
