name: Clang Tidy

on:
  workflow_call:

jobs:
  clang-tidy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to ensure base SHA is available

      - name: Fetch base branch
        run: git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact-${{ github.event.number }}
          path: ${{ github.workspace }}/build

      - name: Run clang-tidy
        run: |
          src_files=$(git diff origin/main --name-only | grep "\.cpp" || true)
          if [ -z "$src_files" ]; then
            echo "No files to check."
          else
            clang-tidy --config-file=./.clang-tidy -p ${{github.workspace}}/build/compile_commands.json -warnings-as-errors='*' $src_files
          fi
